export { default as CopyIcon } from '@mui/icons-material/ContentCopyRounded';
export { default as DeleteIcon } from '@mui/icons-material/DeleteOutlineRounded';
export { default as EditIcon } from '@mui/icons-material/EditRounded';
export { default as ImageIcon } from '@mui/icons-material/ImageRounded';
export { default as UploadIcon } from '@mui/icons-material/UploadRounded';
export { default as AddIcon } from '@mui/icons-material/AddRounded';
export { default as CloseIcon } from '@mui/icons-material/CloseRounded';
export { default as FavoriteOutlinedIcon } from '@mui/icons-material/FavoriteBorderRounded';
export { default as FavoriteFilledIcon } from '@mui/icons-material/FavoriteRounded';
export { default as ShareIcon } from '@mui/icons-material/ShareRounded';
export { default as InfoIcon } from '@mui/icons-material/InfoOutlined';
export { default as ArrowBackIosIcon } from '@mui/icons-material/ArrowBackIosNewRounded';
export { default as ArrowForwardIosIcon } from '@mui/icons-material/ArrowForwardIosRounded';
export { default as ArrowBackIcon } from '@mui/icons-material/ArrowBackRounded';
export { default as ArrowForwardIcon } from '@mui/icons-material/ArrowForwardRounded';
// export { default as CheckCircleIcon } from '@mui/icons-material/CheckCircleRounded';
export { default as RemoveCircleIcon } from '@mui/icons-material/RemoveCircleRounded';
export { default as RemoveIcon } from '@mui/icons-material/RemoveRounded';
export { default as PhoneIcon } from '@mui/icons-material/LocalPhoneRounded';
export { default as EmailIcon } from '@mui/icons-material/AlternateEmailRounded';
export { default as LocationIcon } from '@mui/icons-material/FmdGoodRounded';
export { default as MinusIcon } from '@mui/icons-material/RemoveRounded';
export { default as SyncIcon } from '@mui/icons-material/SyncRounded';
export { default as LaunchIcon } from '@mui/icons-material/LaunchRounded';

export { default as InsertLinkIcon } from '@mui/icons-material/InsertLinkRounded';

export { default as AddImageIcon } from './AddImage';
export { default as CartIcon } from './Cart';
export { default as ShoppingBagIcon } from './ShoppingBag';
export { default as CheckCircleIcon } from './CheckCircle';
export { default as ShoppingBagAddIcon } from './ShoppingBagAdd';
export { default as UsersIcon } from './UsersIcon';
export { default as GroupsIcon } from './GroupsIcon';
export { default as UserIcon } from './UserIcon';
export { default as KeyboardArrowRightIcon } from './KeyboardArrowRight';
